# S3c24XX Platform Support
snd-soc-s3c-objs := s3c-pcm.o
snd-soc-s3c-i2s-objs := s3c-i2s.o
snd-soc-s3c2443-ac97-objs := s3c2443-ac97.o
snd-soc-s3c2450-ac97-objs := s3c2450-ac97.o
snd-soc-s3c2450-i2s-objs  := s3c2450-i2s.o
snd-soc-s3c2416-i2s-objs  := s3c2416-i2s.o
snd-soc-s3c6400-ac97-objs := s3c6400-ac97.o
snd-soc-s3c6410-i2s-objs  := s3c6410-i2s-v40.o
snd-soc-s3c6410-pcmif-objs  := s3c6410-pcmif.o

obj-$(CONFIG_SND_S3C_SOC) += snd-soc-s3c.o
obj-$(CONFIG_SND_S3C_SOC_I2S) += snd-soc-s3c-i2s.o
obj-$(CONFIG_SND_S3C2443_SOC_AC97) += snd-soc-s3c2443-ac97.o
obj-$(CONFIG_SND_S3C2450_SOC_AC97) += snd-soc-s3c2450-ac97.o
obj-$(CONFIG_SND_S3C2450_SOC_I2S) += snd-soc-s3c2450-i2s.o
obj-$(CONFIG_SND_S3C2416_SOC_I2S) += snd-soc-s3c2416-i2s.o
obj-$(CONFIG_SND_S3C6400_SOC_AC97) += snd-soc-s3c6400-ac97.o
obj-$(CONFIG_SND_S3C6410_SOC_I2S) += snd-soc-s3c6410-i2s.o
obj-$(CONFIG_SND_S3C6410_SOC_AC97) += snd-soc-s3c6400-ac97.o
obj-$(CONFIG_SND_S3C6410_SOC_PCMIF) += snd-soc-s3c6410-pcmif.o

# S3C24XX Machine Support
snd-soc-smdk2416-wm8753-objs := smdk2416_wm8753.o
snd-soc-smdk2416-wm8731-objs := smdk2416_wm8731.o
snd-soc-smdk2443-wm9710-objs := smdk2443_wm9710.o
snd-soc-smdk2450-wm9713-objs := smdk2450_wm9713.o
snd-soc-smdk2450-wm8580-objs := smdk2450_wm8580.o
snd-soc-smdk2450-wm8753-objs := smdk2450_wm8753.o
snd-soc-smdk6400-wm9713-objs := smdk6400_wm9713.o
snd-soc-smdk6400-wm8753-objs := smdk6400_wm8753.o
snd-soc-smdk6400-wm8990-objs := smdk6400_wm8990.o
snd-soc-smdk6410-wm8580-objs := smdk6410_wm8580.o
snd-soc-smdk6410-wm8753-objs := smdk6400_wm8753.o
snd-soc-smdk6410-wm8990-objs := smdk6410_wm8990.o
snd-soc-smdk6410-wm8580-pcmif-objs := smdk6410_wm8580_pcmif.o

obj-$(CONFIG_SND_S3C24XX_SOC_SMDK2416_WM8753) += snd-soc-smdk2416-wm8753.o
obj-$(CONFIG_SND_S3C24XX_SOC_SMDK2416_WM8731) += snd-soc-smdk2416-wm8731.o
obj-$(CONFIG_SND_S3C24XX_SOC_SMDK2443_WM9710) += snd-soc-smdk2443-wm9710.o
obj-$(CONFIG_SND_S3C24XX_SOC_SMDK2450_WM9713) += snd-soc-smdk2450-wm9713.o
obj-$(CONFIG_SND_S3C24XX_SOC_SMDK2450_WM8580) += snd-soc-smdk2450-wm8580.o
obj-$(CONFIG_SND_S3C24XX_SOC_SMDK2450_WM8753) += snd-soc-smdk2450-wm8753.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6400_WM9713) += snd-soc-smdk6400-wm9713.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6400_WM8753) += snd-soc-smdk6400-wm8753.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6400_WM8990) += snd-soc-smdk6400-wm8990.o

# Temporary for 6410
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM9713) += snd-soc-smdk6400-wm9713.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM8580) += snd-soc-smdk6410-wm8580.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM8753) += snd-soc-smdk6400-wm8753.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM8990) += snd-soc-smdk6410-wm8990.o
obj-$(CONFIG_SND_S3C64XX_SOC_SMDK6410_WM8580_PCMIF) += snd-soc-smdk6410-wm8580-pcmif.o
