# arch/arm/mach-s3c2416/Makefile
#
# Copyright 2007 Samsung Electronics
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

obj-$(CONFIG_CPU_S3C2416)	+= s3c2416.o
obj-$(CONFIG_CPU_S3C2416)	+= irq.o
obj-$(CONFIG_CPU_S3C2416)	+= clock.o

obj-$(CONFIG_S3C2416_DMA)	+= dma.o
obj-$(CONFIG_S3C2416_PM)	+= pm.o

# Machine support

obj-$(CONFIG_MACH_SMDK2416)	+= mach-smdk2416.o
